api_platform:
    title: 'Bouledogue français API'
    description: 'This is an Bouledogue français api'
    version: '0.1.0'
    enable_nelmio_api_doc: true
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
